/**
 * Monthly PDF report generator.
 * Uses html-pdf-node (fallback: saves HTML only if PDF renderer unavailable).
 * Triggered by scheduler on 1st of month, or manually via GET /api/reports/generate
 */

const fs   = require('fs');
const path = require('path');
const db   = require('../db/database');

const REPORTS_DIR = path.join(__dirname, '..', 'reports');
if (!fs.existsSync(REPORTS_DIR)) fs.mkdirSync(REPORTS_DIR, { recursive: true });

function getMonthData(year, month) {
  // month is 1-based
  const from = `${year}-${String(month).padStart(2, '0')}-01`;
  const to   = month === 12
    ? `${year + 1}-01-01`
    : `${year}-${String(month + 1).padStart(2, '0')}-01`;

  const leads = db.db.prepare(
    `SELECT * FROM leads WHERE created_at >= ? AND created_at < ? ORDER BY created_at`
  ).all(from, to);

  const prev = db.db.prepare(
    `SELECT COUNT(*) AS total, COUNT(CASE WHEN status='converted' THEN 1 END) AS converted FROM leads WHERE created_at >= ? AND created_at < date(?, '-1 month')`
  ).get(from, from);

  const total     = leads.length;
  const converted = leads.filter(l => l.status === 'converted').length;
  const rate      = total ? Math.round(converted / total * 100) : 0;
  const prevRate  = prev?.total ? Math.round((prev?.converted || 0) / prev.total * 100) : 0;
  const avgScore  = total ? Math.round(leads.reduce((s, l) => s + (l.score || 0), 0) / total * 10) / 10 : 0;

  // By area
  const byArea = {};
  leads.forEach(l => {
    let d = {}; try { d = JSON.parse(l.data || '{}'); } catch (_) {}
    const area = d.area || 'Unknown';
    byArea[area] = (byArea[area] || 0) + 1;
  });
  const bestArea = Object.entries(byArea).sort((a, b) => b[1] - a[1])[0]?.[0] || '—';

  return { leads, total, converted, rate, prevRate, avgScore, byArea, bestArea, year, month };
}

function buildReportHTML(data) {
  const monthName = new Date(data.year, data.month - 1, 1).toLocaleString('en-AE', { month: 'long', year: 'numeric' });
  const rateChange = data.rate - data.prevRate;
  const changeStr = rateChange >= 0 ? `+${rateChange}%` : `${rateChange}%`;
  const changeColor = rateChange >= 0 ? '#10B981' : '#EF4444';

  const areaRows = Object.entries(data.byArea).sort((a, b) => b[1] - a[1])
    .map(([area, count]) => `<tr><td>${area}</td><td style="font-weight:600">${count}</td></tr>`).join('');

  return `<!DOCTYPE html>
<html>
<head><meta charset="UTF-8">
<style>
  body { font-family: Inter, sans-serif; margin: 0; color: #0F1A35; }
  .header { background: linear-gradient(135deg, #3D7FFA, #06C8E0); padding: 40px; color: white; }
  .header h1 { margin: 0; font-size: 28px; }
  .header p { margin: 8px 0 0; opacity: .8; }
  .content { padding: 40px; }
  .kpi-row { display: grid; grid-template-columns: repeat(4, 1fr); gap: 20px; margin-bottom: 32px; }
  .kpi { background: #F4F6FA; border-radius: 12px; padding: 20px; }
  .kpi .val { font-size: 28px; font-weight: 700; }
  .kpi .lbl { font-size: 12px; color: #5A6A8A; margin-top: 4px; }
  h2 { font-size: 18px; margin: 32px 0 16px; border-bottom: 2px solid #E4E9F2; padding-bottom: 8px; }
  table { width: 100%; border-collapse: collapse; }
  th { text-align: left; padding: 10px; background: #F4F6FA; font-size: 12px; text-transform: uppercase; }
  td { padding: 10px; border-bottom: 1px solid #E4E9F2; font-size: 13px; }
  .footer { background: #1B2236; color: #A8B5CC; padding: 20px 40px; font-size: 12px; margin-top: 40px; }
</style>
</head>
<body>
  <div class="header">
    <h1>📊 ${process.env.CLIENT_NAME || 'WhatsApp Bot'} — Monthly Report</h1>
    <p>${monthName}</p>
  </div>
  <div class="content">
    <div class="kpi-row">
      <div class="kpi"><div class="val">${data.total}</div><div class="lbl">Total Leads</div></div>
      <div class="kpi"><div class="val">${data.rate}%</div><div class="lbl">Conversion Rate <span style="color:${changeColor}">${changeStr} vs prev month</span></div></div>
      <div class="kpi"><div class="val">${data.avgScore}/10</div><div class="lbl">Avg Lead Score</div></div>
      <div class="kpi"><div class="val">${data.bestArea}</div><div class="lbl">Best Performing Area</div></div>
    </div>

    <h2>Leads by Area</h2>
    <table>
      <thead><tr><th>Area</th><th>Leads</th></tr></thead>
      <tbody>${areaRows}</tbody>
    </table>

    <h2>Recent Leads</h2>
    <table>
      <thead><tr><th>Name</th><th>WhatsApp</th><th>Score</th><th>Status</th><th>Date</th></tr></thead>
      <tbody>${data.leads.slice(0, 20).map(l => `
        <tr>
          <td>${l.name || '—'}</td>
          <td>${l.wa_number}</td>
          <td>${l.score || 0}/10</td>
          <td>${l.status}</td>
          <td>${l.created_at?.slice(0, 10)}</td>
        </tr>`).join('')}
      </tbody>
    </table>
  </div>
  <div class="footer">
    Generated by ${process.env.CLIENT_NAME || 'WhatsApp Bot'} CRM · ${new Date().toLocaleString('en-AE', { timeZone: 'Asia/Dubai' })}
  </div>
</body>
</html>`;
}

async function generateReport(year, month) {
  if (!year || !month) {
    const now = new Date();
    year  = now.getFullYear();
    month = now.getMonth() + 1;
  }

  const data     = getMonthData(year, month);
  const html     = buildReportHTML(data);
  const filename = `report-${year}-${String(month).padStart(2, '0')}`;
  const htmlPath = path.join(REPORTS_DIR, filename + '.html');

  fs.writeFileSync(htmlPath, html);
  console.log('[Report] HTML saved:', htmlPath);

  // Try puppeteer for PDF
  try {
    const puppeteer = require('puppeteer');
    const browser = await puppeteer.launch({ args: ['--no-sandbox', '--disable-setuid-sandbox'] });
    const page    = await browser.newPage();
    await page.setContent(html, { waitUntil: 'networkidle0' });
    const pdfPath = path.join(REPORTS_DIR, filename + '.pdf');
    await page.pdf({ path: pdfPath, format: 'A4', printBackground: true });
    await browser.close();
    console.log('[Report] PDF saved:', pdfPath);
    return { filename: filename + '.pdf', path: pdfPath };
  } catch (err) {
    console.warn('[Report] Puppeteer not available, HTML-only report saved:', err.message);
    return { filename: filename + '.html', path: htmlPath };
  }
}

function listReports() {
  try {
    return fs.readdirSync(REPORTS_DIR)
      .filter(f => f.endsWith('.pdf') || f.endsWith('.html'))
      .map(f => ({
        filename: f,
        size: fs.statSync(path.join(REPORTS_DIR, f)).size,
        created: fs.statSync(path.join(REPORTS_DIR, f)).mtime.toISOString(),
      }))
      .sort((a, b) => b.created.localeCompare(a.created));
  } catch (_) { return []; }
}

module.exports = { generateReport, listReports, REPORTS_DIR };
